/**
 * @file brand-docs/generate.ts
 * @description Deterministic generator that turns the design system index +
 * a complete brief into DESIGN.md and PRODUCT.md markdown. No I/O, no LLM —
 * the startup path must be reproducible without an agent in the loop.
 *
 * Split: PRODUCT.md = who & why (verbal atoms + audience + voice words).
 * DESIGN.md = how it looks (visual atoms + references + anti-references + tone).
 * Degrades gracefully: missing atoms are noted, never thrown on.
 */

import type { DesignSystemIndex } from '../indexer/types.js';
import type { MotionSystem } from '../types/design-system.js';
import type { Brief } from './brief.js';

const HEADER_NOTE =
  '> Generated by brandkit-mcp from the brand atomic system + the brief in `brandkit.config.yaml`.\n' +
  '> Edits outside the `brandkit-mcp` delimiter block are preserved; the block is overwritten on each regeneration.';

function section(title: string, body: string): string {
  const trimmed = body.trim();
  return `## ${title}\n\n${trimmed || '_Not defined in the brand atomic system._'}\n`;
}

/** Split a free-text answer on newlines/semicolons into a bullet list. */
function bullets(text: string): string {
  const items = text
    .split(/[\n;]+/)
    .map((s) => s.trim())
    .filter(Boolean);
  if (items.length <= 1) return text.trim();
  return items.map((i) => `- ${i}`).join('\n');
}

function renderCustomProps(props: Record<string, string>): string {
  const entries = Object.entries(props);
  if (entries.length === 0) return '';
  return [
    '| Token | Value |',
    '| --- | --- |',
    ...entries.map(([k, v]) => `| \`${k}\` | \`${v}\` |`),
  ].join('\n');
}

function renderMotion(motion: MotionSystem): string {
  const lines: string[] = [];
  if (motion.tokens && typeof motion.tokens === 'object') {
    const keys = Object.keys(motion.tokens as Record<string, unknown>);
    if (keys.length) {
      lines.push(`Motion tokens: ${keys.map((k) => `\`${k}\``).join(', ')}.`);
    }
  }
  if (typeof motion.css === 'string' && motion.css.length > 0) {
    lines.push(`Motion CSS is defined in agent/visual/motion/motion.css (${motion.css.length} chars).`);
  }
  return lines.join('\n\n');
}

function buildProduct(index: DesignSystemIndex, brief: Brief): string {
  const v = index.verbal;
  const audienceBody =
    brief.audience +
    (v.audience
      ? `\n\nFrom the brand's audience definition:\n\n\`\`\`json\n${JSON.stringify(v.audience.data, null, 2)}\n\`\`\``
      : '');
  const voiceBody =
    `In three words: **${brief.voice_words}**.` + (v.voice ? `\n\n${v.voice.body.trim()}` : '');

  return [
    `# ${index.brandName} — Product Brief`,
    '',
    HEADER_NOTE,
    '',
    section('Who this is for', audienceBody),
    section('Brand voice', voiceBody),
    section('Positioning', v.positioning?.body ?? ''),
    section('Messaging', v.messaging?.body ?? ''),
    section('Differentiation', v.differentiation?.body ?? ''),
    section('Concepts', v.concepts?.body ?? ''),
  ].join('\n');
}

function buildDesign(index: DesignSystemIndex, brief: Brief): string {
  const b = index.base;
  const colorBlock = b.colorsAndType ? renderCustomProps(b.colorsAndType.customProperties) : '';
  const fontsBlock = b.fonts.length
    ? b.fonts
        .map(
          (f) =>
            `- **${f.family}**${f.weight != null ? ` ${f.weight}` : ''}` +
            `${f.style && f.style !== 'normal' ? ` ${f.style}` : ''}`,
        )
        .join('\n')
    : '';
  const componentsBlock = b.components.length
    ? b.components
        .map((c) => {
          const displayName = c.name.charAt(0).toUpperCase() + c.name.slice(1);
          return (
            `- **${displayName}** (${c.category})` +
            `${c.description ? ` — ${c.description}` : ''}` +
            `${c.variants?.length ? ` · variants: ${c.variants.join(', ')}` : ''}`
          );
        })
        .join('\n')
    : '';
  const motionBlock = b.motion ? renderMotion(b.motion) : '';

  return [
    `# ${index.brandName} — Design Brief`,
    '',
    HEADER_NOTE,
    '',
    section('Audience & tone', `The product should feel: **${brief.voice_words}**.\n\nBuilt for: ${brief.audience}`),
    section('Visual references', bullets(brief.visual_references)),
    section('Anti-references — do NOT look like these', bullets(brief.anti_references)),
    section('Color & typography tokens', colorBlock),
    section('Fonts', fontsBlock),
    section('Components', componentsBlock),
    section('Motion', motionBlock),
  ].join('\n');
}

/** Build both reference documents from the index + a complete brief. */
export function generateBrandDocs(
  index: DesignSystemIndex,
  brief: Brief,
): { design: string; product: string } {
  return { product: buildProduct(index, brief), design: buildDesign(index, brief) };
}
